apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitnami-sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  path: ./bitnami-sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure