apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: 8-demo
  namespace: flux-system
spec:
  image: docker.io/p12kumar1998/bb-demo-test
  interval: 10s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: 8-demo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: 8-demo
  policy:
    semver:
      range: 7.8.x
