apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: 8-demo
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: 8-demo
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: 8-demo
  interval: 1m40s
  sourceRef:
    kind: GitRepository
    name: 8-demo
  update:
    path: ./manifests
    strategy: Setters
